repos:
-   repo: https://github.com/psf/black
    rev: 23.1.0  # key required by pre-commit, but ignored in practice, because we use the "system" version of the tool, set in setup.cfg
    hooks:
    -   id: black
        language: system
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1  # key required by pre-commit, but ignored in practice, because we use the "system" version of the tool, set in setup.cfg
    hooks:
    -   id: mypy
        args: []
        language: system
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.254  # key required by pre-commit, but ignored in practice, because we use the "system" version of the tool, set in setup.cfg
    hooks:
    -   id: ruff
        language: system
