[project]
name = "taxes"
version = "1.0.0"
license = { text = "Proprietary" }
requires-python = ">=3.10"
dependencies = [
    "PyPDF2 < 3.0",
    "camelot-py[all]",
    "click",
    "pandas",
]

[project.optional-dependencies]
testing = [
    "black",
    "mypy",
    "pandas-stubs",
    "pre-commit",
    "pytest",
    "ruff",
    "syrupy",
    "types-python-dateutil",
    "wcmatch",
]

[project.scripts]
statements2csv = "statements2csv.__main__:main"

[tool.ruff]
select = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "I",
  "N",
  "UP",
  "W",
]
# E501 - line too long; if Black does its job, I'm not worried about the rare long line
ignore = ["E501"]

[tool.ruff.per-file-ignores]
"**/tests/**/*" = ["D103"]

[tool.ruff.pydocstyle]
convention = "pep257"

[tool.pytest.ini_options]
addopts = [
  '--snapshot-default-extension',
  'tests.statements2csv.snapshot_extensions.CryptAwareExtension',
]
